name: EBAC CI - Cypress Suite

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22
            cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar testes do Cypress
        run: npm run test:ci
        continue-on-error: true

      - name: Publish Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report